version: '3.8'

services:
  payments:
    container_name: payments
    build: .
    command: /bin/sh -c "python3 manage.py makemigrations && python3 manage.py migrate &&
                      python3 manage.py spectacular --color --file schema.yml &&
                      python3 manage.py runserver 0.0.0.0:8000
                      "
    volumes:
      - .:/payments
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:14.6-alpine
    env_file:
      - .env
    restart: unless-stopped